@startuml uml-activity mephi fin_project

skinparam monochrome true
skinparam backgroundColor #F9F9F9
skinparam componentStyle filled

start

repeat
:Пользователь вводит данные для авторизации;
:Система проверяет введенные данные;

repeat while (Авторизация успешна?) is (нет)
  :Пользователь выбирает дальнейшее действие;

split
  partition "Действие с транзакцией" {
    :Пользователь выбирает действие с транзакцией;

    if (Создание транзакции?) then (да)
      repeat
        :Пользователь заполняет форму новой транзакции;
        repeat while (Валидация данных успешна?) is (нет)
        :Система сохраняет транзакцию;
        :Пользователь получает подтверждение;
    else if (Редактирование транзакции?) then (да)
        repeat
        :Пользователь вводит изменения;
        repeat while (Валидация данных успешна?) is (нет)
        :Система обновляет данные;
        :Пользователь получает подтверждение;
    else if (Удаление транзакции?) then (да)
        repeat
        :Пользователь выбирает транзакцию для удаления;
        repeat while (Валидация данных успешна?) is (нет)
        :Система обновляет данные;
        :Пользователь получает подтверждение;
    endif
  
  stop
  }

split again
  partition "Работа с дашбордами" {
  :Пользователь выбирает раздел "Дашборды";
  
  if (Отчет с фильтрами) then (да)
  repeat

  :Пользователь задает фильтры;
  repeat while (Фильтры валидны?) is (нет)
  endif 
  fork
    :Система извлекает и преобразовывает данные для дашборда 1;
  fork again
    :Система извлекает и преобразовывает данные для дашборда N;
  end fork
  :Система собирает все данные в общий интерфейс;
  :Пользователь просматривает отчёты;

  stop
  }
end split

@enduml

